apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: bank-usac/account-service
    newTag: dev
  - name: bank-usac/api-gateway
    newTag: dev
  - name: bank-usac/customer-service
    newTag: dev
  - name: bank-usac/payment-service
    newTag: dev
  - name: bank-usac/transaction-service
    newTag: dev
  - name: bank-usac/notification-audit-service
    newTag: dev
  - name: bank-usac/frontend
    newTag: dev
