apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-usac-config
  namespace: bank-usac
data:
  ENTORNO: desarrollo
  CORS_ORIGINS: "http://__PUBLIC_HOST__"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: bank-usac
data:
  ACTIVATION_LINK_BASE: "http://__PUBLIC_HOST__/activar"
