apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - rabbitmq.yaml
  - api-gateway.yaml
  - customer-service.yaml
  - account-service.yaml
  - payment-service.yaml
  - transaction-service.yaml
  - frontend.yaml
