UPDATE pagos SET estado='PENDIENTE' WHERE estado IN ('VALIDANDO_KYC','VALIDANDO_CUENTA');
ALTER TABLE pagos DROP CONSTRAINT IF EXISTS ck_pagos_estado;
ALTER TABLE pagos
    ADD CONSTRAINT ck_pagos_estado CHECK (estado IN ('PENDIENTE','PROCESANDO','COMPENSANDO','COMPLETADO','RECHAZADO'));
