ALTER TABLE pagos DROP CONSTRAINT IF EXISTS ck_pagos_estado;
ALTER TABLE pagos
    ADD CONSTRAINT ck_pagos_estado CHECK (estado IN ('PENDIENTE','VALIDANDO_KYC','VALIDANDO_CUENTA','PROCESANDO','COMPENSANDO','COMPLETADO','RECHAZADO'));
